# -*- coding: utf-8 -*-
"""Tanzania_Solar_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wwNc60UrY4G_158kfSpy21hBwav0Jusl
"""

!pip install geemap

"""Install the Libraries"""

import ee
import os
import geemap

ee.Authenticate()

ee.Initialize(project="")

countries_lev0 = ee.FeatureCollection("FAO/GAUL/2015/level0")

Tanzania_boundary = countries_lev0.filter(ee.Filter.eq("ADM0_NAME", "United Republic of Tanzania"))

"""Load Solar Data"""

solar = ee.ImageCollection("ECMWF/ERA5_LAND/MONTHLY_AGGR")\
          .filterDate("2024-01-01","2024-12-31")\
          .select("surface_solar_radiation_downwards_sum")\
          .mean()\
          .multiply(2.77778e-7)
solar_tanzania = solar.clip(Tanzania_boundary)

"""Visualization"""

map_tz = geemap.Map()
tanzania_vis ={
    "min":150,
    "max":190,
    "palette":["blue","green","yellow","orange","red"]
}

map_tz.centerObject(Tanzania_boundary,6)
map_tz.addLayer(solar_tanzania,tanzania_vis, "Tanzania Solar Potential")
map_tz.add_colorbar(tanzania_vis, label="Solar Radiation(kWh/m²)", layer_name="Tanzania Solar Potential",orientation="horizontal",transparent_bg=True)

map_tz.centerObject(Tanzania_boundary,6)

map_tz

map_tz.to_html(filename="Tanzania_Solar_Project.html")